github:
  description: "Apache Seata(incubating) Website"
  homepage: https://seata.apache.org/
  enabled_merge_buttons:
    squash:  true
    merge:   false
    rebase:  false
  dependabot_alerts:  true
  dependabot_updates: false
  protected_branches:
    docusaurus: {}
    develop: {}
notifications:
  commits: notifications@seata.apache.org
  issues: dev@seata.apache.org
  pullrequests: dev@seata.apache.org
  discussions: notifications@seata.apache.org

publish:
  whoami: asf-site
  hostname: seata.apache.org