github:
  description: "Apache Seata(incubating) Website"
  homepage: https://seata.apache.org/
  enabled_merge_buttons:
    squash:  true
    merge:   false
    rebase:  false
  dependabot_alerts:  true
  dependabot_updates: false
  protected_branches:
    docusaurus:
      required_conversation_resolution: true
      required_status_checks:
        strict: true
      required_pull_request_reviews:
        dismiss_stale_reviews: false
        required_approving_review_count: 1
    develop: {}
notifications:
  commits: notifications@seata.apache.org
  issues: dev@seata.apache.org
  pullrequests: dev@seata.apache.org
  discussions: notifications@seata.apache.org

publish:
  whoami: asf-site
