/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    {
      type: 'category',
      label: 'Overview',
      collapsible: false,
      items: ['overview/what-is-seata', 'overview/terminology', 'overview/faq'],
    },
    {
      type: 'category',
      label: 'User Doc',
      collapsible: false,
      items: [
        'user/quickstart',
        'user/configurations',
        'user/api',
        'user/microservice',
        {
          type: 'category',
          label: 'SQL Reference',
          items: ['user/sqlreference/sql-restrictions', 'user/sqlreference/dml'],
        },
      ],
    },
    {
      type: 'category',
      label: 'Developer Guide',
      collapsible: false,
      items: [
        {
          type: 'category',
          label: 'Transaction Mode',
          items: ['dev/mode/at-mode', 'dev/mode/tcc-mode', 'dev/mode/saga-mode'],
        },
        'dev/seata-mertics',
      ],
    },
    {
      type: 'category',
      label: 'Ops Guide',
      collapsible: false,
      items: [
        'ops/upgrade',
        {
          type: 'category',
          label: 'Deploy',
          items: ['ops/deploy-server', 'ops/deploy-by-docker', 'ops/deploy-by-kubernetes', 'ops/deploy-by-helm', 'ops/deploy-ha'],
        },
      ],
    },
  ],
  developers: [
    {
      type: 'category',
      label: 'Developers List',
      collapsible: false,
      items: ['developers/developers_dev'],
    },
    {
      type: 'category',
      label: 'Contribute Guide',
      collapsible: false,
      items: [
        'developers/contributor-guide/new-contributor-guide_dev',
        'developers/contributor-guide/test-coverage-guide_dev',
        'developers/contributor-guide/reporting-security-issues_dev',
        'developers/guide_dev',
      ],
    },
    {
      type: 'category',
      label: 'Committer Guide',
      collapsible: false,
      items: [
        'developers/committer-guide/label-an-issue-guide_dev',
        'developers/committer-guide/website-guide_dev',
        'developers/committer-guide/release-guide_dev',
      ],
    },
  ],
  download: [
    {
      type: 'category',
      label: 'Download',
      collapsible: false,
      items: ['download'],
    },
  ],
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
