name: seata.io deploy on oss

on:
  push:
    branches:
      - docusaurus
  #This schedule only takes effect in the default branch
  schedule:
    - cron: '0 */12 * * *'

jobs:
  Build-Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 19.5.x
        uses: actions/setup-node@v1
        with:
          node-version: 19.5.x
      - name: Build
        run: |
          npm install && npm run build
          mkdir sitemaps && node sitemap.js
          mkdir deploy-dist && cp -R build/* deploy-dist/
          mv sitemaps .htaccess *.txt *.xml deploy-dist/
        env:
          ALGOLIA_APIKEY: ${{secrets.ALGOLIA_APIKEY}}
      - name: Use Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - run: npm i @serverless-devs/s -g  --registry=https://registry.npmmirror.com
      - run: s config add --AccountID ${{secrets.ACCOUNT_ID}}  --AccessKeyID ${{secrets.ACCESS_KEYID}}  --AccessKeySecret ${{secrets.ACCESS_KEYSECRET}} -a seata -f
      - name: Deploy
        run: s deploy --use-local -y
