name: seata.io deploy on oss

on:
  push:
    branches:
      - docusaurus

jobs:
  Build-Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - run: npm i @serverless-devs/s -g  --registry=https://registry.npmmirror.com
      - run: s config add --AccountID ${{secrets.ACCOUNT_ID}}  --AccessKeyID ${{secrets.ACCESS_KEYID}}  --AccessKeySecret ${{secrets.ACCESS_KEYSECRET}} -a seata -f
      - name: Deploy
        run: s deploy --use-local -y
