name: Doc Lint

on: [pull_request]

jobs:
  markdownlint:
    name: Markdown lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19.5.x'
      - run: npm i
      - run: npm run lint
