name: test_gen_sitemaps

on: [pull_request]

jobs:
  Build-Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 19.5.x
        uses: actions/setup-node@v1
        with:
          node-version: 19.5.x
      - name: Build
        run: |
          npm install && npm run build
          mkdir sitemaps && node sitemap.js
          mkdir deploy-dist && cp -R build/* deploy-dist/
          mv sitemaps .htaccess *.txt *.xml deploy-dist/
        env:
          ALGOLIA_APIKEY: ${{secrets.ALGOLIA_APIKEY}}
