name: test_gen_sitemaps

on: [pull_request]

jobs:
  Build-Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: Build
        run: |
          npm install && npm run build
          mkdir sitemaps && node sitemaps.js --apiKey ${{secrets.ALGOLIA_APIKEY}}
          mkdir deploy-dist && cp -R build/* deploy-dist/
          mv sitemaps .htaccess *.txt *.xml deploy-dist/
